import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          Header
        </header>
        {children}
        <footer style={{ backgroundColor: "red", padding: "1rem" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
