import { Metadata } from "next";
import AuthNav from "./auth-nav";
import AuthInput from "./auth-input";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div style={{ backgroundColor: "lightblue", padding: "1rem" }}>
        <AuthNav />
        <AuthInput />
      </div>
      {children}
    </>
  );
}
